### ISSUE TITLE
Getting Error Sass::SyntaxError - Undefined variable: "$filter-field-seperator-width"

### ISSUE THREAD

**Issue by Asnadatta** [vinhnglx/active_bootstrap_skin#11]
I am using activeadmin (1.0.0). I found active_bootstrap_skin pretty simple using in my new project but when I try it on my existing project it crashed let me share logs.
sass::SyntaxError - Undefined variable: "$filter-field-seperator-width".:
  sass (3.4.19) lib/sass/script/tree/variable.rb:49:in `_perform'
  sass (3.4.19) lib/sass/script/tree/node.rb:50:in`perform'
  sass (3.4.19) lib/sass/tree/visitors/perform.rb:395:in `visit_prop'
  sass (3.4.19) lib/sass/tree/visitors/base.rb:36:in`visit'
  sass (3.4.19) lib/sass/tree/visitors/perform.rb:158:in `block in visit'
  sass (3.4.19) lib/sass/stack.rb:79:in`block in with_base'
  sass (3.4.19) lib/sass/stack.rb:115:in `with_frame'
  sass (3.4.19) lib/sass/stack.rb:79:in`with_base'
  sass (3.4.19) lib/sass/tree/visitors/perform.rb:158:in `visit'
  sass (3.4.19) lib/sass/tree/visitors/perform.rb:431:in`block (2 levels) in visit_rule'
  sass (3.4.19) lib/sass/tree/visitors/perform.rb:431:in `block in visit_rule'
  sass (3.4.19) lib/sass/tree/visitors/perform.rb:179:in`with_environment'
  sass (3.4.19) lib/sass/tree/visitors/perform.rb:429:in `visit_rule'
  sass (3.4.19) lib/sass/tree/visitors/base.rb:36:in`visit'
  sass (3.4.19) lib/sass/tree/visitors/perform.rb:158:in `block in visit'
  sass (3.4.19) lib/sass/stack.rb:79:in`block in with_base'
  sass (3.4.19) lib/sass/stack.rb:115:in `with_frame'
  sass (3.4.19) lib/sass/stack.rb:79:in`with_base'
  sass (3.4.19) lib/sass/tree/visitors/perform.rb:158:in `visit'
  sass (3.4.19) lib/sass/tree/visitors/perform.rb:431:in`block (2 levels) in visit_rule'
  sass (3.4.19) lib/sass/tree/visitors/perform.rb:431:in `block in visit_rule'
  sass (3.4.19) lib/sass/tree/visitors/perform.rb:179:in`with_environment'
  sass (3.4.19) lib/sass/tree/visitors/perform.rb:429:in `visit_rule'
  sass (3.4.19) lib/sass/tree/visitors/base.rb:36:in`visit'
  sass (3.4.19) lib/sass/tree/visitors/perform.rb:158:in `block in visit'
  sass (3.4.19) lib/sass/stack.rb:79:in`block in with_base'
  sass (3.4.19) lib/sass/stack.rb:115:in `with_frame'
  sass (3.4.19) lib/sass/stack.rb:79:in`with_base'
  sass (3.4.19) lib/sass/tree/visitors/perform.rb:158:in `visit'
  sass (3.4.19) lib/sass/tree/visitors/perform.rb:431:in`block (2 levels) in visit_rule'
  sass (3.4.19) lib/sass/tree/visitors/perform.rb:431:in `block in visit_rule'
  sass (3.4.19) lib/sass/tree/visitors/perform.rb:179:in`with_environment'
  sass (3.4.19) lib/sass/tree/visitors/perform.rb:429:in `visit_rule'
  sass (3.4.19) lib/sass/tree/visitors/base.rb:36:in`visit'
  sass (3.4.19) lib/sass/tree/visitors/perform.rb:158:in `block in visit'
  sass (3.4.19) lib/sass/stack.rb:79:in`block in with_base'
  sass (3.4.19) lib/sass/stack.rb:115:in `with_frame'
  sass (3.4.19) lib/sass/stack.rb:79:in`with_base'
  sass (3.4.19) lib/sass/tree/visitors/perform.rb:158:in `visit'
  sass (3.4.19) lib/sass/tree/visitors/perform.rb:431:in`block (2 levels) in visit_rule'
  sass (3.4.19) lib/sass/tree/visitors/perform.rb:431:in `block in visit_rule'
  sass (3.4.19) lib/sass/tree/visitors/perform.rb:179:in`with_environment'
  sass (3.4.19) lib/sass/tree/visitors/perform.rb:429:in `visit_rule'
  sass (3.4.19) lib/sass/tree/visitors/base.rb:36:in`visit'
  sass (3.4.19) lib/sass/tree/visitors/perform.rb:158:in `block in visit'
  sass (3.4.19) lib/sass/stack.rb:79:in`block in with_base'
  sass (3.4.19) lib/sass/stack.rb:115:in `with_frame'
  sass (3.4.19) lib/sass/stack.rb:79:in`with_base'
  sass (3.4.19) lib/sass/tree/visitors/perform.rb:158:in `visit'
  sass (3.4.19) lib/sass/tree/visitors/perform.rb:326:in`block (2 levels) in visit_import'
  sass (3.4.19) lib/sass/tree/visitors/perform.rb:326:in `block in visit_import'
  sass (3.4.19) lib/sass/stack.rb:88:in`block in with_import'
  sass (3.4.19) lib/sass/stack.rb:115:in `with_frame'
  sass (3.4.19) lib/sass/stack.rb:88:in`with_import'
  sass (3.4.19) lib/sass/tree/visitors/perform.rb:323:in `visit_import'
  sass (3.4.19) lib/sass/tree/visitors/base.rb:36:in`visit'
  sass (3.4.19) lib/sass/tree/visitors/perform.rb:158:in `block in visit'
  sass (3.4.19) lib/sass/stack.rb:79:in`block in with_base'
  sass (3.4.19) lib/sass/stack.rb:115:in `with_frame'
  sass (3.4.19) lib/sass/stack.rb:79:in`with_base'
  sass (3.4.19) lib/sass/tree/visitors/perform.rb:158:in `visit'
  sass (3.4.19) lib/sass/tree/visitors/base.rb:52:in`block in visit_children'
  sass (3.4.19) lib/sass/tree/visitors/base.rb:52:in `visit_children'
  sass (3.4.19) lib/sass/tree/visitors/perform.rb:167:in`block in visit_children'
  sass (3.4.19) lib/sass/tree/visitors/perform.rb:179:in `with_environment'
  sass (3.4.19) lib/sass/tree/visitors/perform.rb:166:in`visit_children'
  sass (3.4.19) lib/sass/tree/visitors/base.rb:36:in `block in visit'
  sass (3.4.19) lib/sass/tree/visitors/perform.rb:186:in`visit_root'
  sass (3.4.19) lib/sass/tree/visitors/base.rb:36:in `visit'
  sass (3.4.19) lib/sass/tree/visitors/perform.rb:157:in`visit'
  sass (3.4.19) lib/sass/tree/visitors/perform.rb:8:in `visit'
  sass (3.4.19) lib/sass/tree/root_node.rb:36:in`css_tree'
  sass (3.4.19) lib/sass/tree/root_node.rb:20:in `render'
  sass (3.4.19) lib/sass/engine.rb:278:in`render'
  compass-rails (3.0.0) lib/compass-rails/patches/sass_importer.rb:48:in `evaluate'
  tilt (2.0.1) lib/tilt/template.rb:96:in`render'
  sprockets (3.5.2) lib/sprockets/legacy_tilt_processor.rb:25:in `call'
  sprockets (3.5.2) lib/sprockets/processor_utils.rb:75:in`call_processor'
  sprockets (3.5.2) lib/sprockets/processor_utils.rb:57:in `block in call_processors'
  sprockets (3.5.2) lib/sprockets/processor_utils.rb:56:in`call_processors'
  sprockets (3.5.2) lib/sprockets/loader.rb:134:in `load_from_unloaded'
  sprockets (3.5.2) lib/sprockets/loader.rb:60:in`block in load'
  sprockets (3.5.2) lib/sprockets/loader.rb:318:in `fetch_asset_from_dependency_cache'
  sprockets (3.5.2) lib/sprockets/loader.rb:44:in`load'
  sprockets (3.5.2) lib/sprockets/cached_environment.rb:20:in `block in initialize'
  sprockets (3.5.2) lib/sprockets/cached_environment.rb:47:in`load'
  sprockets (3.5.2) lib/sprockets/bundle.rb:23:in `block in call'
  sprockets (3.5.2) lib/sprockets/utils.rb:183:in`dfs'
  sprockets (3.5.2) lib/sprockets/bundle.rb:24:in `call'
  sprockets (3.5.2) lib/sprockets/processor_utils.rb:75:in`call_processor'
  sprockets (3.5.2) lib/sprockets/processor_utils.rb:57:in `block in call_processors'
  sprockets (3.5.2) lib/sprockets/processor_utils.rb:56:in`call_processors'
  sprockets (3.5.2) lib/sprockets/loader.rb:134:in `load_from_unloaded'
  sprockets (3.5.2) lib/sprockets/loader.rb:60:in`block in load'
  sprockets (3.5.2) lib/sprockets/loader.rb:318:in `fetch_asset_from_dependency_cache'
  sprockets (3.5.2) lib/sprockets/loader.rb:44:in`load'
  sprockets (3.5.2) lib/sprockets/cached_environment.rb:20:in `block in initialize'
  sprockets (3.5.2) lib/sprockets/cached_environment.rb:47:in`load'
  sprockets (3.5.2) lib/sprockets/base.rb:66:in `find_asset'
  sprockets (3.5.2) lib/sprockets/environment.rb:30:in`find_asset'
  sprockets (3.5.2) lib/sprockets/base.rb:92:in `[]'
  sprockets-rails (2.3.3) lib/sprockets/rails/helper.rb:230:in`lookup_asset_for_path'
  sprockets-rails (2.3.3) lib/sprockets/rails/helper.rb:190:in `check_errors_for'
  sprockets-rails (2.3.3) lib/sprockets/rails/helper.rb:159:in`block in stylesheet_link_tag'
  sprockets-rails (2.3.3) lib/sprockets/rails/helper.rb:158:in `stylesheet_link_tag'

**Comment by Asnadatta** [comment]
solved by adding these in active_admin.scss
$filter-field-seperator-width: 20px;
$side-by-side-filter-input-width: 20px;
